name: Build and Deploy Documentation (Alternative)

on:
  workflow_dispatch:
    inputs:
      use_alternative:
        description: 'Use alternative build method'
        required: false
        default: 'true'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages-alt"
  cancel-in-progress: true

jobs:
  # Build job with alternative method
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          cache: 'npm'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Install GitBook CLI globally
        run: |
          npm install -g gitbook-cli
          gitbook install book

      - name: Build documentation with GitBook
        run: |
          cd book
          gitbook build . ../_site
          
          # Create a .nojekyll file to bypass Jekyll processing
          touch ../_site/.nojekyll
          
          # Copy any additional assets if needed
          if [ -d "../static" ]; then
            cp -r ../static/* ../_site/
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
